### ISSUE TITLE
Active Spring Network not loading sites

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/GroundWaterWatch#41]
Can we confirm that we're making the correct call to their services so I can go back to Jessica and ask what's up?

**Comment by jknewson** [comment]
The last I talked w/ Jessica, they mentioned they were working on it, however, I think we should bring it up just to be sure. We currently have the network code specified as 'SPR' for the spring network.

**Comment by HansVraga** [comment]
Jessica has confirmed the issue is on her end.
