### ISSUE TITLE
Layers/Basemaps - remove State/County Label, Rename button

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/GroundWaterWatch#47]
GW no longer wants these in the Legend.
![image](https://cloud.githubusercontent.com/assets/12058013/19036306/09edd0de-893d-11e6-85dd-5e307935c70f.png)

**Comment by HansVraga** [comment]
~~Linda would like to keep the option to turn these on and off, so please just update the label (don't remove them from the selection)~~

Now they want them gone.

**Comment by HansVraga** [comment]
Rename button from "Legend" to "Base Maps" to reflect its new use.

**Comment by marsmith** [comment]
addressed with #65.  i dont think we can kill the legend completely since this should contain the legend for the GWW sites
