### ISSUE TITLE
Link to site broken?

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/GroundWaterWatch#50]
Site in screenshot links to: 
http://groundwaterwatch.usgs.gov/AWLSites.asp?S=434342090495601&ncd=30List
"The specified URL cannot be found." in a new tab.

![image](https://cloud.githubusercontent.com/assets/12058013/19037520/bcc7d31a-8944-11e6-90fe-1910a88617ff.png)

**Comment by jknewson** [comment]
fixed with #51
