### ISSUE TITLE
Populate Long Term Network information

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/GroundWaterWatch#53]
Looks like we missed a page: 

![image](https://cloud.githubusercontent.com/assets/12058013/19125736/378c04d2-8b06-11e6-92e2-c185b1d50567.png)

**Comment by HansVraga** [comment]
The Long-Term Groundwater Data network consists of actively-measured periodic, continuous, and/or real-time wells with at least 20 years of measurements. These pages offer the user a choice of various measurement frequencies along with various lengths of records. By selecting a combination of frequency and length of record radio buttons, a user can select data sets of interest, organized by state. 

Measurement Frequencies
The following measurement frequencies are selectable in these pages 

Annual Data:
at least 1 measurement per year (includes monthly and daily wells)
Monthly Data:
at least 1 measurement per month (includes daily wells)
Daily Data:
at least 1 measurement per day.
Length of Record
The user can select from the following lengths of record: 

20 years: 20 or more years of record (includes data in 30 and 50 year data set)
30 years: 30 or more years of record (includes data in 50 year data set)
50 years: 50 or more years of record. 

To be included in the data set, the well record must be 80% complete over the period of interest. For example, selecting wells with 30 years of monthly data means that all wells in the data set will have at least 288 months of measurements (30 yrs x 12 months x 80%). 

By selecting among the various frequency and length of record radio buttons, a user can select the datasets of interest, organized by state.

Groundwater Watch is maintained by the Office of Groundwater.

**Comment by mitch-wim** [comment]
For this issue, it looks like the content _**is**_ in the source (ncd.js), it's just not displaying. I'm not exactly sure how the content in the modal gets displayed, so probably better for someone else to handle.

**Comment by marsmith** [comment]
done
