### ISSUE TITLE
Use Production GWW map services

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/GroundWaterWatch#54]
https://cida.usgs.gov/gww-geoserver/

uses https:// - otherwise everything 'the same'

**Comment by HansVraga** [comment]
More Details below - with these the site/state/county pages should work again.

> Linda,
> 
> I investigated the reason for the broken QA url that you noticed earlier this week and somehow our connection to the database became disabled. When I re-enabled it the service appears to be back to normal. The two previously remaining hold ups for testing were 1) the need to update to the WaterML2 Water Service which have the appropriate data aging flags, 2) an issue with our fetcher that caused the same ~2500 sites to get fetched everytime and then the remaining would never get populated. Both issues have since been resolved.
> 
> We are still seeing some of the sites in the networks ETL from GWW failing because of file formatting, but I'll work out those issues with George next week. 
> 
> Barbara let me know that you are interested in 4 different requests for state, county, site, and national level. All of those are possible with the current service, but require at least 1 network to be specified. Here are example requests:
> 
> By Network: http://cida-test.er.usgs.gov/gww-geoserver/groundwaterwatch/wms?service=WMS&version=1.1.0&request=GetMap&layers=groundwaterwatch:Latest_WL_Percentile&styles=&bbox=-159.5758333,17.994131949445,-65.99433208,61.2900096992059&width=768&height=355&srs=EPSG:4269&format=application/openlayers&CQL_FILTER=NETWORK_CD=%27CRN%27
> 
> By State: http://cida-test.er.usgs.gov/gww-geoserver/groundwaterwatch/wms?service=WMS&version=1.1.0&request=GetMap&layers=groundwaterwatch:Latest_WL_Percentile&styles=&bbox=-159.5758333,17.994131949445,-65.99433208,61.2900096992059&width=768&height=355&srs=EPSG:4269&format=application/openlayers&CQL_FILTER=(NETWORK_CD=%27AWL%27)AND(STATE_CD=%2712%27)
> 
> By County:
> http://cida-test.er.usgs.gov/gww-geoserver/groundwaterwatch/wms?service=WMS&version=1.1.0&request=GetMap&layers=groundwaterwatch:Latest_WL_Percentile&styles=&bbox=-159.5758333,17.994131949445,-65.99433208,61.2900096992059&width=768&height=355&srs=EPSG:4269&format=application/openlayers&CQL_FILTER=(NETWORK_CD=%27AWL%27)AND(STATE_CD=%2712%27)AND(COUNTY_CD=%27095%27)
> 
> By Site:
> http://cida-test.er.usgs.gov/gww-geoserver/groundwaterwatch/wms?service=WMS&version=1.1.0&request=GetMap&layers=groundwaterwatch:Latest_WL_Percentile&styles=&bbox=-159.5758333,17.994131949445,-65.99433208,61.2900096992059&width=768&height=355&srs=EPSG:4269&format=application/openlayers&CQL_FILTER=FID=%20%27USGS.265138082002201%27
> 
> You can also use the CQL filter in the service interface to test the filters, which might be easier than formatting the URLs.

**Comment by HansVraga** [comment]
@jknewson Do you recall, is this done?

**Comment by marsmith** [comment]
This is done:

![image](https://user-images.githubusercontent.com/6529123/28276711-c0f4d27a-6ae5-11e7-9745-0157d636554a.png)
