### ISSUE TITLE
Change Left Panel display

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/GroundWaterWatch#56]
Three tasks here:
- [x] Remove panning/zooming functions in left-hand panel. The Networks should be fixed at a national view.
- [x] Remove "States" from the "Other" section.
- [x] Change Panel to reflect the following (see description, mock-ups):

> cluster of 3 maps (mainland and Puerto Rico/Virgin Islands, Alaska, Hawaii) with a heading.  Each heading is collapsible such that the opening page shows the Active Groundwater Level Network expanded and the other networks just show headers.
> ![image](https://cloud.githubusercontent.com/assets/12058013/19658090/a7890094-99f4-11e6-9658-32b2c3a8fc99.png)

**Comment by marsmith** [comment]
I dont think its feasible to do 3 seperate leaflet maps for each network.  I'll turn off pan and zoom linking and zoom the extent out

**Comment by marsmith** [comment]
implemented
