### ISSUE TITLE
Update integration with George's GWW pages

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/GroundWaterWatch#60]
To create a full "prototype" system, upgrade our links to George's GWW pages to point to his TEST pages that have the new map code. Example URLS below:

http://groundwaterwatch.usgs.gov/StateMapTEST.asp?sa=CA&sc=06
http://groundwaterwatch.usgs.gov/countymapTEST.asp?sa=MA&cc=001
http://groundwaterwatch.usgs.gov/awlsitesTEST.asp?S=374004122092102

**Comment by jknewson** [comment]
moved redirect link to appconfig file and updated the above links to point to the ones listed. I tried to add 'TEST' to the other network redirects, but doesn't exist.
such as http://groundwaterwatch.usgs.gov/netmapT4L1TEST.asp?ncd=AKU. #61
