### ISSUE TITLE
Add "National Aquifer Composite Hydrographs" to Primary Network Section

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/GroundWaterWatch#64]
- [x] Shoe-horn in an image with the map previews in the left-hand panel. 
- [x] Add "?" text as seen in this screenshot
- [x] Clicking on this section opens (http://152.61.235.95/composite.asp) in a new tab

![image](https://cloud.githubusercontent.com/assets/12058013/22554482/2512c490-e92e-11e6-98b9-0dfa4f0b667b.png)

Image can be found:
https://groundwaterwatch.usgs.gov/compositemap.html

https://groundwaterwatch.usgs.gov/composite.asp

**Comment by marsmith** [comment]
addressed
